config/routes.rb
Rails.application.routes.draw do
  passwordless_for :members, at: "/", as: "passwordless"

  resources :members do
    collection do
      delete "batch"
      post "import"
      post "register"
    end
  end

  resources :groups do
    collection do
      delete "batch"
      post "import"
    end

    resources :memberships, only: [:create, :destroy]
  end

  resources :registrations

  resources :settings

  resources :registration_campaigns

  get "home", to: "root#home"

  root to: "root#index"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :uuid             not null, primary key
#  description :string
#  email       :string
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_groups_on_name  (name) UNIQUE
#
class Group < ApplicationRecord
  # Group model relationships
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships
  has_many :current_members, -> {
    current.distinct
  }, through: :memberships, source: :member

  # Default group is a hidden group where registered member end up
  DEFAULT_GROUP_NAME = "default".freeze

  # Group model query interface (scopes)
  # By default, don't search for the "DEFAULT_GROUP"
  default_scope do
    where.not(name: DEFAULT_GROUP_NAME)
  end
  scope :default_group, -> { unscoped.where(name: DEFAULT_GROUP_NAME) }
  scope :current, -> { joins(:memberships).merge(Membership.current).distinct }

  # Group model validations
  validates :name, uniqueness: true
  validates :name, :description, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, allow_blank: true, uniqueness: true

  # Full text search capabilities
  include PgSearch::Model
  pg_search_scope :search,
    against: [:name, :description],
    using: {
      tsearch: {prefix: true, any_word: true}
    }

  def self.default
    Group.default_group.first
  rescue ActiveRecord::RecordNotFound => e
    Rails.logger.warn <<~MSG
      #{e}
      You don't seem to have seeded initial database data. Try this:

      > bundle exec rake seed
    MSG
  end

  def is_default?
    name == DEFAULT_GROUP_NAME
  end
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id             :uuid             not null, primary key
#  address        :text             not null
#  city           :string           not null
#  dob            :date             not null
#  email          :string           not null
#  first_name     :string           not null
#  last_name      :string           not null
#  phone          :string
#  role           :integer          not null
#  sexe           :integer          not null
#  workflow_state :string           not null
#  zipcode        :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  parent_id      :uuid
#
# Indexes
#
#  index_members_on_email                                    (email) UNIQUE
#  index_members_on_f_unaccent_first_name_text_gin_trgm_ops  (f_unaccent((first_name)::text) gin_trgm_ops) USING gin
#  index_members_on_f_unaccent_last_name_text_gin_trgm_ops   (f_unaccent((last_name)::text) gin_trgm_ops) USING gin
#  index_members_on_parent_id                                (parent_id)
#
class Member < ApplicationRecord
  FEMALE = :female
  MALE = :male
  SEXES = [FEMALE, MALE]

  ROLE_ADMIN = :admin
  ROLE_BASIC = :basic
  ROLES = [ROLE_ADMIN, ROLE_BASIC]

  IMPORT_FIELDS = [
    :first_name,
    :last_name,
    :email,
    :dob,
    :sexe,
    :address,
    :city,
    :zipcode,
    :phone,
    :workflow_state,
    "memberships.year",
    :parent_id
  ]

  # The FSGT websites requires a particular CSV format to be able to upload licences requests.
  FSGT_EXPORT_FIELDS = [
    :last_name,
    :first_name,
    "dob AS birthday",
    "CASE sexe WHEN 1 THEN 'M' WHEN 0 THEN 'F' END AS gender",
    :address,
    "'' AS address2",
    "'' AS address3",
    "zipcode AS zip_code",
    :city,
    "'Oui' AS insurance",
    "'' AS home_phone_number",
    "'' AS pro_phone_number",
    "phone AS phone_number",
    :email,
    "'' AS license_id",
    "'' AS license_type"
  ]

  EXPORT_FIELDS = IMPORT_FIELDS + [
    :id
  ]

  UPDATE_FIELDS = [
    :phone,
    :address, :zipcode, :city
  ]
  CREATION_FIELDS = UPDATE_FIELDS + [
    :first_name, :last_name, :dob, :sexe,
    :email,
    :parent_id, :workflow_state
  ]

  enum sexe: SEXES
  enum role: ROLES

  # Member model relationships
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :current_groups, -> {
    current.distinct
  }, through: :memberships, source: :group

  belongs_to :parent, class_name: "Member", optional: true
  has_many :children, class_name: "Member", foreign_key: "parent_id", inverse_of: :parent, dependent: :nullify

  # Member model validations and initialisations
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: {case_sensitive: false}
  validates :dob, :sexe, :address, :zipcode, :city, presence: true
  before_create :build_with_defaults

  # Member query interfaces (scopes)
  scope :current, -> { year(Time.current.year) }
  scope :current_children, -> { current.select("children_members.*").left_outer_joins(:children) }
  scope :year, ->(year) { joins(:memberships).merge(Membership.only_year(year)).distinct }
  scope :no_membership, -> { where.missing(:memberships).distinct }

  # Authentication mechanism via 'Password-less' logins
  passwordless_with :email

  # Member model workflow (state and transitions)
  include WorkflowActiverecord
  workflow do
    state :candidate do
      event :draw, transitions_to: :selected
    end
    state :selected do
      event :subscribe, transitions_to: :registered, if: :valid_subscription?
    end
    state :expired do
      event :renewal, transitions_to: :registered, if: :valid_subscription?
    end
    state :registered do
      event :expire, transitions_to: :expired
    end
  end

  # Full text search capabilities
  include PgSearch::Model
  pg_search_scope :search,
    against: [:first_name, :last_name],
    ignoring: :accents,
    using: {
      trigram: {word_similarity: true}
    }

  public

  def active?
    self.class.current.where(id: id).present?
  end

  def latest_membership
    memberships.order(:year).last
  end

  def age
    ActiveSupport::Duration.build(Time.zone.now - dob.to_time).parts[:years]
  end

  def name
    "#{first_name} #{last_name}"
  end

  def admin?
    role.to_s == ROLE_ADMIN.to_s
  end

  def to_s
    "#<#{self.class}:#{id} state=#{workflow_state} name=#{name}>"
  end

  def self.create_from_raw!(raw_attributes)
    attributes = raw_attributes.symbolize_keys
    member = attributes.slice(*IMPORT_FIELDS)

    if member[:sexe].present? && SEXES.exclude?(member[:sexe].to_sym)
      member[:sexe] = SEXES[member[:sexe].to_i]
    end

    if attributes[:year].present?
      member[:memberships] = [
        Membership.new({group: Group.default}.merge(attributes.extract!(:year)))
      ]
    end

    create!(member)
  end

  private

  # TODO
  def valid_subscription?
    true
  end

  def build_with_defaults
    # All members have basic role by default
    self.role = Member::ROLE_BASIC
    self.workflow_state ||= :candidate
  end
end

app/controllers/groups_controller.rb
class GroupsController < AuthenticatedController
  skip_load_resource only: :show

  def index
    defaults = {limit: Setting.cached_or_find_by_key(Setting::CONFIGURABLE_LISTING_PER_PAGE), offset: 0}

    @index_params = index_params
    @limit, @offset =
      @index_params
        .with_defaults(defaults)
        .slice(:limit, :offset)
        .values
    @page = @offset.to_i / @limit + 1
    @search = @index_params[:search]
    @order = @index_params[:order]

    @groups = @groups.search(@search) if @search.present?
    @groups = @groups.order(@order.to_h) if @order
    @total = @groups.count
    @groups = @groups.limit(@limit).offset(@offset)

    respond_to_html_json_csv(
      @groups,
      V1::GroupSerializer,
      csv_columns: [:name, :description]
    )
  end

  def new
  end

  def edit
  end

  def create
    if @group.save
      flash[:info] = I18n.t("groups.new.success")

      redirect_to group_path(@group)
    else
      if @group.errors.any?
        flash[:error] = render_activerecord_errors(@group.errors)
      end

      render action: :new
    end
  end

  def show
    @group = Group.includes([:current_members]).find(params[:id])

    respond_to_html_json_csv(
      @group,
      V1::GroupSerializer
    )
  end

  def update
    if update_params.present? && @group.update(update_params)
      flash[:info] = I18n.t("groups.update.success")

      redirect_to group_path(@group)
    elsif @group.errors.any?
      flash[:error] = render_activerecord_errors(@group.errors)
      redirect_to edit_group_path(@group)
    else
      redirect_to group_path(@group)
    end
  end

  def batch
    @groups = Group.where(id: params[:group_ids])

    if @groups.present?
      @destroyed_groups = @groups.destroy_all

      flash[:warning] = I18n.t(
        "groups.batch.success",
        element: helpers.pluralize(@destroyed_groups.count, I18n.t("activerecord.models.group"))
      )

      redirect_to groups_path
    end
  end

  def import
    file = import_params
    created = 0

    CSV.foreach(file.path, headers: true) do |row|
      Group.create!(row.to_hash)
      created += 1
    end

    flash[:info] = I18n.t("groups.import.success", created: created)

    redirect_to groups_path
  rescue => e
    flash[:warning] = I18n.t("groups.import.failure", created: created, message: e.message)

    redirect_to groups_path
  end

  private

  def index_params
    params.permit(
      :search,
      :offset,
      order: [:created_at, :name]
    )
  end

  def create_params
    params.require(:group).permit(:name, :description, :email)
  end

  def update_params
    create_params
  end

  def import_params
    params.require(:import_file)
  end
end

app/views/groups/_form.html.erb
<div class="container">
  <%= form_with model: [group], local: true, class: "row" do |form| %>
    <fieldset class="col-12">
      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :name, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>


      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :description, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.text_area :description, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :email, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.text_field :email, class: "form-control" %>
        </div>
      </div>
    </fieldset>

    <fieldset class="col-12">
      <div class="form-group row">
        <div class="col-md-10">
          <%= form.submit nil, class: 'btn btn-primary' %>
          <%= link_to I18n.t('back'), session[:return_to], class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/groups/_import_modal.html.erb
<div class="modal fade" id="importGroupMembersModal" tabindex="-1" role="dialog" aria-labelledby="importGroupMembersModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <%= form_with url: import_groups_url, method: :post do |form| %>
      <div class="modal-header">
        <h5 class="modal-title" id="importMembersModalTitle"><%= t('members.index.modals.import.title') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <div class="col-md-3">
            <%= form.label t('members.index.modals.import.file_input'), class: "col-form-label" %>
          </div>
          <div class="col-md-9">
            <%= form.file_field :import_file, accept: 'text/csv', class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('members.index.modals.import.buttons.cancel') %></button>
        <%= form.submit t('members.index.modals.import.buttons.import'), class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<h1><%= t('groups.update.title') %></h1>

<%= render partial: "form", locals: {group: @group}%>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>

app/views/groups/index.html.erb
<%= render partial: "import_modal" %>

<h1><%= t('groups.index.title') %></h1>

<div class="row mt-3">
 <div class="col-sm-6">
   <%= form_with method: "get" do |form| %>
     <div class="input-group mb-3">
       <%= form.text_field :search, placeholder: t('groups.index.buttons.search'), value: @search, class: "form-control" %>
       <div class="input-group-append">
         <%= form.submit("🔎", class: 'btn btn-outline-secondary input-group-text', id: 'button-addon2') %>
       </div>
     </div>
   <% end %>
  </div>
  <div class="col-sm-6">
    <div class="dropdown float-sm-right mb-3">
      <% if can?(:destroy, Group) %>
        <%= button_tag(type: "submit",
                       data: { confirm: "Are you sure ?" },
                       form: "delete_groups_form",
                       class: "btn btn-sm btn-outline-danger") do %>
          Delete groups
        <% end %>
      <% end %>

      <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#importGroupMembersModal">
        <%= t('members.index.buttons.import') %>
      </button>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <% if @groups.present? %>
      <%= form_with id:"delete_groups_form", url: batch_groups_url, method: :delete do |f| %>
        <div class="table-responsive-sm">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col"><%= t('activerecord.models.group.attributes.name') %>
                  <%= order_link(:name, order: @order) %>
                </th>
                <th scope="col"><%= t('activerecord.models.group.attributes.description') %>
                </th>
                <th scope="col"><%= t('activerecord.models.group.attributes.created_at') %>
                  <%= order_link(:created_at, order: @order) %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @groups.each do |group| %>
                <tr class="clickable-row">
                  <th scope="row"><%= f.check_box 'group_ids[]', {}, group.id, nil %></th>
                    <td>
                      <%= link_to group.name, group_url(group) %>
                      <small>(<%= group.current_members.count %>)</small>
                    </td>
                    <td><%= group.description %></td>
                    <td><%= l group.created_at, format: :short %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-6">
          </div>
          <div class="col-6">
            <% if can?(:create, Group) %>
              <%= link_to "➕ #{t('groups.index.buttons.create')}",
                          new_group_path,
                          class: 'btn btn-sm btn-outline-primary float-right' %>
              <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <b>
        <% if @search.blank? %>
          <%= t('groups.index.empty') %>
        <% else %>
          <%= t('groups.index.empty_search', search: @search) %>
        <% end %>
      </b>
    <% end %>
  </div>
</div>

<%= render partial: "shared/pagination",
    locals: {
      collection: @groups,
      current_page: @page,
      link_params: @index_params,
      per_page: @limit,
      offset: @offset,
      total: @total
    }
%>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>

app/views/groups/new.html.erb
<h1><%= t('groups.new.title') %></h1>

<%= render partial: "form", locals: {group: @group}%>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>

app/views/groups/show.html.erb
<div class="row mb-3">
  <div class="col">
    <% if can?(:update, @group) %>
    <p class="float-right">
      <%= link_to "#{t('groups.show.edit_button')} 📝", edit_group_path(@group), class: 'btn btn-primary btn-sm' %>
    </p>
    <% end %>

    <h1><%= t('groups.show.title', name: @group.name) %></h1>

    <div class="float-none mb-3">
      <span class="text-muted font-italic">
        <small>
          <%= t('groups.show.created_at', date: @group.created_at.to_date) %>
        </small>
      </span>
      <div class="badges">
      <% if @group.email.present? %>
        <span class="badge badge-info">💌 <%= mail_to @group.email, @group.email, class: "text-light" %></span>
      <% end %>
      </div>
    </div>

    <div class="lead"><%= @group.description %></div>
  </div>
</div>

<div class="row mb-3">
  <div class="col-sm-8">
    <h2><%= t('groups.show.members_list') %></h2>
    <ul class="list-group">
      <% if @group.current_members.present? %>
        <% @group.current_members.select("members.*, memberships.id AS membership_id").each do |member| %>
          <li class="list-group-item member">
            <%= link_to member.name, member_url(member) %>

            <% if can?(:destroy, Membership) %>
              <span class="float-right">
                <%= form_with(url: group_membership_url(@group, member.membership_id), local: true, method: :delete) do |f| %>
                  <%= f.submit('❌', class: 'btn btn-sm btn-outline-danger', data: { confirm: t('groups.show.buttons.confirm') }) %>
                <% end %>
              </span>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <li class="list-group-item">
          <b>
            <%= t('groups.show.empty_members') %>
          </b>
        </li>
      <% end %>

      <% if can?(:create, Membership) %>
      <li class="list-group-item font-italic">
        <%= form_with model: [@group, Membership.new], local: true do |form| %>
          <div class="input-group mb-3">
            <%= form.text_field :member_name, autocomplete: "off", class: "form-control", id: "autoComplete", placeholder: "#{t('groups.show.new_member')}", "data-autocomplete": "#{members_path}.json", "data-autocomplete-minchars": 3, "data-autocomplete-param-name": "search", "data-autocomplete-search-attr-name": "name", "data-autocomplete-select-attr-name": "id" %>
            <%= form.hidden_field :member_id, class: "autoComplete_selected" %>
            <div class="input-group-append">
              <%= form.submit "➕", class: 'btn btn-outline-secondary' %>
            </div>
          </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
  <p><%= @group.to_json %></p>
<% end %>