config/routes.rb
Rails.application.routes.draw do
  passwordless_for :members, at: "/", as: "passwordless"

  resources :members do
    collection do
      delete "batch"
      post "import"
      post "register"
    end
  end

  resources :groups do
    collection do
      delete "batch"
      post "import"
    end

    resources :memberships, only: [:create, :destroy]
  end

  resources :registrations

  resources :settings

  resources :registration_campaigns

  get "home", to: "root#home"

  root to: "root#index"
end

app/views/shared/_flashes.html.erb
<% if flash.present? %>
<div class="flashes row justify-content-center fixed-top mt-3">
  <div class="col-sm-4 m-3">
    <% flash.each do |name, msgs| -%>
      <% [msgs].flatten.each do |msg| %>
        <%= content_tag :div, class: "alert alert-#{flash_to_bootstrap_alert(name)} fade show", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= msg.try(:html_safe) %>
        <% end %>
      <% end %>
    <% end -%>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer l-box bg-dark">
  <p class="small">
    <%= t('footer.signature') %>
  </p>

  <% if Rails.env.development? %>
    <div class="small debug">
      <% if content_for(:debug) %>
        <%= yield(:debug) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_head.html.erb
<title><%= local_assigns[:title] ? local_assigns[:title] : 'Grimpe Club' %></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= favicon_pack_tag 'static/favicon.png', rel: 'shortcut icon apple-touch-icon', type: 'image/png' %>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_nav-item.html.erb
<div class="nav-item">
  <% is_active = current_controller?([locals[:path]]) ? "active" : "" %>
  <%= link_to locals[:path], class: "nav-link font-weight-bold text-light bg-success #{is_active}" do %>
    <span class='menu-icon'><%= locals[:icon] %></span>
    <%= yield %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="nav-vertical navbar-dark bg-success" id="sidebar">
  <button id="sidebarCollapse" class="bg-success text-light navbar-toggle close" type="button">
    <span class="cross" aria-hidden="true">&laquo;</span>
    <span class="arrow" aria-hidden="true">&raquo;</span>
    <!-- <span class="navbar-toggler-icon"></span> -->
  </button>

  <p class="font-weight-bold text-uppercase px-3 small pb-4 mb-0">
    <%= link_to(Rails.application.routes.url_helpers.root_path, class: "navbar-brand") do %>
      <%= club_name %>
    <% end %>
  </p>

  <div class="nav flex-column bg-success mb-0">
    <%= render("shared/nav-item", locals: {icon: "🏡", path: Rails.application.routes.url_helpers.root_path}) do %>
      <%= t('nav.home') %>
    <% end %>
    <% if can?(:manage, Member) %>
      <%= render("shared/nav-item", locals: {icon: "👨‍👩‍👧‍👦", path: members_path}) do %>
        <%= t('nav.members') %>
      <% end %>
    <% end %>
    <% if can?(:index, Group) %>
      <%= render("shared/nav-item", locals: {icon: "🧰", path: groups_path}) do %>
        <%= t('nav.groups') %>
      <% end %>
    <% end %>
    <% if can?(:index, Registration) %>
      <%= render("shared/nav-item", locals: {icon: "📅", path: registrations_path}) do %>
        <%= t('nav.registrations') %>
      <% end %>
    <% end %>
    <%# TODO: Uncomment this entry when the full migration to the RegistrationCampaign model has been finished %>
    <%# <% if can?(:index, RegistrationCampaign) %1> %>
    <%#   <%= render("shared/nav-item", locals: {icon: "📅", path: registration_campaigns_path}) do %1> %>
    <%#     <%= t('nav.registrations') %1> %>
    <%#   <% end %1> %>
    <%# <% end %1> %>
    <% if can?(:index, Setting) %>
      <%= render("shared/nav-item", locals: {icon: "🛠️", path: settings_path}) do %>
        <%= t('nav.settings') %>
      <% end %>
    <% end %>
  </div>

  <div class="logged-in text-white">
    <div class="nav flex-column bg-success mb-0">
      <% if current_user.present? %>
        <%= render("shared/nav-item", locals: {icon: emoji_sexe(current_user.sexe), path: member_path(current_user)}) do %>
          <span class="font-italic font-weight-lighter"><%= t('nav.connected') %></span>
          <h5 class="m-0 font-weight-bolder"><%= current_user.name %></h5>
        <% end %>
        <%= render("shared/nav-item", locals: {icon: "🚪️", path: send(Passwordless.mounted_as).sign_out_path})  do %>
          <%= t('nav.sign_out') %>
        <% end %>
      <% else %>
        <%= render("shared/nav-item", locals: {icon: "➡️", path: send(Passwordless.mounted_as).sign_in_path}) do %>
          <%= t('nav.sign_in') %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_pagination.html.erb
<% unless current_page == 1 && collection.size < per_page %>
<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="d-flex">
      <div class="m-auto p-2">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item <% if current_page == 1 %>disabled<% end %>">
              <%= link_to(link_params.merge(offset: 0), class: "page-link", aria: {disabled: (current_page == 1)}) do %>
                <span aria-hidden="true">&laquo;</span>
              <% end %>
            </li>
            <% if current_page > 1 %>
              <% if current_page > 2 %>
                <li class="page-item disabled"><a class="page-link" href="#">…</a></li>
              <% end %>
              <li class="page-item">
                <%= link_to  (current_page.to_i - 1), link_params.merge(offset: (offset.to_i - per_page.to_i)), class: "page-link" %>
              </li>
            <% end %>
            <li class="page-item active"><a class="page-link" href="#"><%= current_page %></a></li>
            <% if collection.size == per_page %>
              <li class="page-item">
                <%= link_to  (current_page.to_i + 1), link_params.merge(offset: (offset.to_i + per_page.to_i)), class: "page-link" %>
              </li>
              <li class="page-item disabled"><a class="page-link" href="#">…</a></li>
            <% end %>
            <li class="page-item <% if collection.size < per_page %>disabled<% end %>">
              <%= link_to(link_params.merge(offset: total - (total % per_page)), class: "page-link", data: {"aria-disabled": (collection.size < per_page)}) do %>
                <span aria-hidden="true">&raquo;</span>
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<% end %>