config/routes.rb
Rails.application.routes.draw do
  passwordless_for :members, at: "/", as: "passwordless"

  resources :members do
    collection do
      delete "batch"
      post "import"
      post "register"
    end
  end

  resources :groups do
    collection do
      delete "batch"
      post "import"
    end

    resources :memberships, only: [:create, :destroy]
  end

  resources :registrations

  resources :settings

  resources :registration_campaigns

  get "home", to: "root#home"

  root to: "root#index"
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id         :uuid             not null, primary key
#  s_key      :string
#  s_value    :binary
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Setting < ApplicationRecord
  CONFIGURABLE_KEYS = {
    CONFIGURABLE_CLUB_NAME = "club.name" => "Grimpe.club",
    CONFIGURABLE_BETA_FEATURE = "beta.feature" => false,
    CONFIGURABLE_LISTING_PER_PAGE = "listing.per_page" => 20
  }.freeze

  before_save :clear_cache
  after_destroy :clear_cache

  validates :s_key, uniqueness: true
  validate :s_value, :non_empty_value

  def initialize(attributes = {})
    attr_key = attributes.delete(:key)
    attr_value = attributes.delete(:value)
    super(attributes)

    self.s_key = attr_key if attr_key
    self.value = attr_value if attr_value
  end

  def non_empty_value
    if !!value && value.blank?
      errors.add(:s_value, "can't be empty")
    end
  end

  def value=(val)
    self.s_value = Marshal.dump(val)
  end

  def value
    Marshal.load(s_value)
  end

  def parse_human_value!
    self.value = self.class.parse_human_value(value)
  end

  def clear_cache
    self.class.clear_cache(s_key)
  end

  def self.clear_cache(key)
    Rails.cache.delete_matched("#{name}/single/#{key}")
    Rails.cache.delete_matched("#{name}/all")
  end

  def self.cached_or_find_by_key(key)
    Rails.cache.fetch("#{name}/single/#{key}") do
      value = find_by(s_key: key)&.value
      value.nil? ? CONFIGURABLE_KEYS[key] : value
    end
  end

  def self.config
    custom = Rails.cache.fetch("#{name}/all") {
      custom = all # Select all settings from database
    }

    CONFIGURABLE_KEYS.map { |k, v|
      [
        k,
        custom.find do |s|
          s.s_key == k
        end&.value || v
      ]
    }.to_h
  end

  # Parse value as a string and try to guess the type of object entered
  def self.parse_human_value(value)
    if value.start_with?("[") && value.end_with?("]")
      value[1..-2].split(",").map(&:strip).map do |el|
        parse_human_value(el)
      end
    elsif ["true", "false"].include?(value)
      value == "true"
    elsif value.length == value.to_i.to_s.chars.count
      value.to_i
    else
      value
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < AuthenticatedController
  def index
    @order = order_params[:order]

    if @order
      @settings = @settings.order(@order.to_h)
    end
  rescue ArgumentError
  end

  def create
    @setting.parse_human_value!

    if @setting.save
      flash[:info] = I18n.t("settings.create.success")
    else
      flash[:error] = render_activerecord_errors(@setting.errors)
    end

    redirect_to settings_path
  end

  def destroy
    @setting.destroy
    flash[:alert] = t(".success")

    redirect_to request.referer || settings_path
  end

  private

  def create_params
    params.require(:setting).permit(:key, :value)
  end

  def order_params
    params.permit(order: [:created_at, :s_key])
  end
end

app/views/settings/index.html.erb
<h1><%= t('settings.index.title') %></h1>

<div class="container mt-3">
  <div class="row">
    <div class="col">
      <div>
        <p><%= t('settings.index.subtitle') %></p>
        <p><b><%= t('settings.index.warning').html_safe %></b></p>
      </div>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <% if Setting::CONFIGURABLE_KEYS.present? %>
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th scope="col"><%= t('activerecord.attributes.setting.key') %></th>
              <th scope="col" class="value"><%= t('activerecord.attributes.setting.value') %></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% Setting::CONFIGURABLE_KEYS.each do |key, default| %>
              <% setting = @settings.find_by_s_key(key) %>
              <%= form_with url: settings_path, scope: :setting, local: true, class: "row" do |form| %>
              <tr>
                <td scope="row"><%= key %></td>
                <td scope="row" class="value">
                  <% if setting.present? %>
                    <%= setting.value.inspect %>
                  <% else %>
                    <%= form.hidden_field :key, value: key %>
                    <%= form.text_field :value, value: Setting.cached_or_find_by_key(key), class: "form-control" %>
                  <% end %>
                </td>
                <td>
                  <% if setting.present? %>
                    <%= link_to(setting_url(setting),
                                method: :delete,
                                title: t('settings.index.buttons.default'),
                                class: 'btn-danger btn mx-0',
                                data: { confirm: t('settings.index.buttons.confirm') }) do %>
                      ✗
                  <% end %>
                <% else %>
                  <%= form.submit '✏️ ',
                                  title: t('settings.index.buttons.edit'),
                                  class: 'button btn-outline-primary btn mx-0' %>
                <% end %>
                </td>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
    <% else %>
      <b><%= t('settings.index.empty') %></b>
    <% end %>
  </div>
</div>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>