config/routes.rb
Rails.application.routes.draw do
  passwordless_for :members, at: "/", as: "passwordless"

  resources :members do
    collection do
      delete "batch"
      post "import"
      post "register"
    end
  end

  resources :groups do
    collection do
      delete "batch"
      post "import"
    end

    resources :memberships, only: [:create, :destroy]
  end

  resources :registrations

  resources :settings

  resources :registration_campaigns

  get "home", to: "root#home"

  root to: "root#index"
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id             :uuid             not null, primary key
#  address        :text             not null
#  city           :string           not null
#  dob            :date             not null
#  email          :string           not null
#  first_name     :string           not null
#  last_name      :string           not null
#  phone          :string
#  role           :integer          not null
#  sexe           :integer          not null
#  workflow_state :string           not null
#  zipcode        :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  parent_id      :uuid
#
# Indexes
#
#  index_members_on_email                                    (email) UNIQUE
#  index_members_on_f_unaccent_first_name_text_gin_trgm_ops  (f_unaccent((first_name)::text) gin_trgm_ops) USING gin
#  index_members_on_f_unaccent_last_name_text_gin_trgm_ops   (f_unaccent((last_name)::text) gin_trgm_ops) USING gin
#  index_members_on_parent_id                                (parent_id)
#
class Member < ApplicationRecord
  FEMALE = :female
  MALE = :male
  SEXES = [FEMALE, MALE]

  ROLE_ADMIN = :admin
  ROLE_BASIC = :basic
  ROLES = [ROLE_ADMIN, ROLE_BASIC]

  IMPORT_FIELDS = [
    :first_name,
    :last_name,
    :email,
    :dob,
    :sexe,
    :address,
    :city,
    :zipcode,
    :phone,
    :workflow_state,
    "memberships.year",
    :parent_id
  ]

  # The FSGT websites requires a particular CSV format to be able to upload licences requests.
  FSGT_EXPORT_FIELDS = [
    :last_name,
    :first_name,
    "dob AS birthday",
    "CASE sexe WHEN 1 THEN 'M' WHEN 0 THEN 'F' END AS gender",
    :address,
    "'' AS address2",
    "'' AS address3",
    "zipcode AS zip_code",
    :city,
    "'Oui' AS insurance",
    "'' AS home_phone_number",
    "'' AS pro_phone_number",
    "phone AS phone_number",
    :email,
    "'' AS license_id",
    "'' AS license_type"
  ]

  EXPORT_FIELDS = IMPORT_FIELDS + [
    :id
  ]

  UPDATE_FIELDS = [
    :phone,
    :address, :zipcode, :city
  ]
  CREATION_FIELDS = UPDATE_FIELDS + [
    :first_name, :last_name, :dob, :sexe,
    :email,
    :parent_id, :workflow_state
  ]

  enum sexe: SEXES
  enum role: ROLES

  # Member model relationships
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :current_groups, -> {
    current.distinct
  }, through: :memberships, source: :group

  belongs_to :parent, class_name: "Member", optional: true
  has_many :children, class_name: "Member", foreign_key: "parent_id", inverse_of: :parent, dependent: :nullify

  # Member model validations and initialisations
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: {case_sensitive: false}
  validates :dob, :sexe, :address, :zipcode, :city, presence: true
  before_create :build_with_defaults

  # Member query interfaces (scopes)
  scope :current, -> { year(Time.current.year) }
  scope :current_children, -> { current.select("children_members.*").left_outer_joins(:children) }
  scope :year, ->(year) { joins(:memberships).merge(Membership.only_year(year)).distinct }
  scope :no_membership, -> { where.missing(:memberships).distinct }

  # Authentication mechanism via 'Password-less' logins
  passwordless_with :email

  # Member model workflow (state and transitions)
  include WorkflowActiverecord
  workflow do
    state :candidate do
      event :draw, transitions_to: :selected
    end
    state :selected do
      event :subscribe, transitions_to: :registered, if: :valid_subscription?
    end
    state :expired do
      event :renewal, transitions_to: :registered, if: :valid_subscription?
    end
    state :registered do
      event :expire, transitions_to: :expired
    end
  end

  # Full text search capabilities
  include PgSearch::Model
  pg_search_scope :search,
    against: [:first_name, :last_name],
    ignoring: :accents,
    using: {
      trigram: {word_similarity: true}
    }

  public

  def active?
    self.class.current.where(id: id).present?
  end

  def latest_membership
    memberships.order(:year).last
  end

  def age
    ActiveSupport::Duration.build(Time.zone.now - dob.to_time).parts[:years]
  end

  def name
    "#{first_name} #{last_name}"
  end

  def admin?
    role.to_s == ROLE_ADMIN.to_s
  end

  def to_s
    "#<#{self.class}:#{id} state=#{workflow_state} name=#{name}>"
  end

  def self.create_from_raw!(raw_attributes)
    attributes = raw_attributes.symbolize_keys
    member = attributes.slice(*IMPORT_FIELDS)

    if member[:sexe].present? && SEXES.exclude?(member[:sexe].to_sym)
      member[:sexe] = SEXES[member[:sexe].to_i]
    end

    if attributes[:year].present?
      member[:memberships] = [
        Membership.new({group: Group.default}.merge(attributes.extract!(:year)))
      ]
    end

    create!(member)
  end

  private

  # TODO
  def valid_subscription?
    true
  end

  def build_with_defaults
    # All members have basic role by default
    self.role = Member::ROLE_BASIC
    self.workflow_state ||= :candidate
  end
end

app/controllers/members_controller.rb
require "csv"

class MembersController < AuthenticatedController
  skip_before_action :require_user!, only: :register
  skip_load_resource only: :register

  def index
    authorize! :manage, Member

    load_active_members

    respond_to_html_json_csv(
      @active_members,
      V1::MemberSerializer,
      json_serializer_options: {include: [:groups]},
      csv_columns: Member::FSGT_EXPORT_FIELDS
    )
  end

  def new
  end

  def edit
  end

  def create
    if @member.save
      flash[:info] = t(".success")

      redirect_to member_path(@member)
    else
      if @member.errors.any?
        flash[:error] = render_activerecord_errors(@member.errors)
      end

      render :new
    end
  end

  def register
    @registration = Registration.where(public: current_user.blank?).ongoing.first

    if @registration.nil?
      flash[:warning] = I18n.t("members.register.not_open")
      redirect_to root_path and return
      return
    end

    # We manually load_resource and authorize_resource
    @member = Member.new(register_params)
    authorize! :register, @member

    if @member.save
      flash[:info] = t(".success")
    elsif @member.errors.any?
      flash[:error] = render_activerecord_errors(@member.errors)
    end

    render "root/index"
  end

  def update
    if update_params.present? && @member.update(update_params)
      flash[:info] = I18n.t("members.update.success")

      redirect_to member_path(@member)
    else
      if @member.errors.any?
        flash[:error] = render_activerecord_errors(@member.errors)
      end

      render :edit
    end
  end

  def batch
    @members = @members.where(id: params[:ids])

    if @members.present?
      @destroyed_members = @members.destroy_all

      flash[:warning] = I18n.t(
        "members.batch.success",
        element: helpers.pluralize(@destroyed_members.count, I18n.t("activerecord.models.member"))
      )

      redirect_to members_path
    end
  end

  def import
    file = import_params
    created = 0

    CSV.foreach(file.path, headers: true) do |row|
      Member.create_from_raw!(row.to_hash)
      created += 1
    end

    flash[:info] = I18n.t("members.import.success", created: created)

    redirect_to members_path
  rescue => e
    flash[:warning] = I18n.t("members.import.failure", created: created, message: e.message)

    redirect_to members_path
  end

  def show
    @member ||= current_user

    @sessions = @member.passwordless_sessions.order(updated_at: :desc).select(
      :remote_addr, :user_agent, :claimed_at
    )

    respond_to_html_json_csv(
      @member,
      V1::MemberSerializer,
      json_serializer_options: {include: [:groups]},
      csv_columns: [:first_name, :last_name, :email, :dob, :id]
    )
  end

  private

  def load_active_members
    defaults = {
      limit: Setting.cached_or_find_by_key(Setting::CONFIGURABLE_LISTING_PER_PAGE),
      offset: 0,
      year: Time.current.year
    }

    @index_params = index_params
    @limit, @offset, @year =
      @index_params
        .with_defaults(defaults)
        .slice(:limit, :offset, :year)
        .values
    @search = @index_params[:search]
    @order = @index_params[:order]
    @years = Membership.select(:year).distinct(:year).order(year: :desc).all

    @active_members = if @year.to_i != 0
      @members.year(@year)
    else
      @members.no_membership
    end
    if @search.present?
      # Bug of pg_search with `.distinct` scope
      # https://github.com/Casecommons/pg_search/issues/238#issuecomment-543702501
      @active_members = @active_members.search(@search).reorder("")
    end
    @page = @offset.to_i / @limit + 1
    @total = @active_members.count
    unless request.format.csv? && index_params[:export] == "all"
      @active_members = @active_members.limit(@limit).offset(@offset)
    end
    @active_members = @active_members.order(@order.to_h) if @order

    # Build families for HTML rendering
    if request.format.html?
      load_families
    end
  end

  def load_families
    members = @active_members.group_by(&:parent_id)
    @families = []
    # Load families with parents first
    parents = members.delete(nil) || []
    parents.each do |parent|
      @families << ([parent] + [members.delete(parent.id)]).flatten.compact
    end
    # Load “orphan” children if any (and fetch their parent /!\ +1 query)
    members.values.each do |children|
      @families << ([children.first.parent] + children).flatten.compact
    end
  end

  def update_params
    if can?(:manage, Member)
      create_params
    else
      params.require(:member).permit(*Member::UPDATE_FIELDS)
    end
  end

  def create_params
    params.require(:member).permit(*Member::CREATION_FIELDS)
  end

  def register_params
    create_params.merge(workflow_state: :candidate)
  end

  def import_params
    params.require(:import_file)
  end

  def index_params
    params.permit(
      :search,
      :autocomplete,
      :offset,
      :year,
      :export,
      order: [:created_at, :last_name, :first_name, :workflow_state]
    )
  end
end

app/views/members/_export_modal.html.erb
<div class="modal fade" id="exportMembersModal" tabindex="-1" role="dialog" aria-labelledby="exportMembersModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exportMembersModalTitle"><%= t('members.index.modals.export.title') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('members.index.modals.export.buttons.cancel') %></button>
        <%= link_to request.query_parameters.merge(format: 'csv', export: 'all'), class: "btn btn-outline-primary" do %>
          <%= t('members.index.modals.export.buttons.export_all') %>
        <% end %>
        <%= link_to request.query_parameters.merge(format: 'csv'), class: "btn btn-primary" do %>
          <%= t('members.index.modals.export.buttons.export') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/_form.html.erb
<div class="container">
  <%= form_with **form_destination.merge(local: true, class: "row") do |form| %>
    <fieldset class="col-md-6">
      <legend><%= t('members.new.basic_details') %></legend>
      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :first_name, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.text_field :first_name, class: "form-control", disabled: !permitted_attributes.include?(:first_name) %>
        </div>
      </div>


      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :last_name, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.text_field :last_name, class: "form-control", disabled: !permitted_attributes.include?(:last_name) %>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-3">
            <%= form.label :sexe, class: "col-form-label pt-0" %>
          </div>
          <div class="col-md-9">
            <div class="form-check">
              <%= form.radio_button :sexe, :male, class: "form-check-input", disabled: !permitted_attributes.include?(:sexe) %>
              <%= form.label :sexe, :male, value: :male, class: "form-check-label" %>
            </div>
            <div class="form-check">
              <%= form.radio_button :sexe, :female, class: "form-check-input", disabled: !permitted_attributes.include?(:sexe) %>
              <%= form.label :sexe, :female, value: :female, class: "form-check-label" %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :date_of_birth, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.date_field :dob, start_year: 1900, end_year: Time.current.year, class: "form-control", disabled: !permitted_attributes.include?(:dob) %>
        </div>
      </div>

      <% if current_user&.admin? %>
      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :family, class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= form.collection_select :parent_id, Member.accessible_by(current_ability).all, :id, :name, {include_blank: true}, {class: "form-control", disabled: !permitted_attributes.include?(:parent_id)} %>
        </div>
      </div>
      <!-- <div class="form-group row"> -->
      <!--   <div class="col-md-3"> -->
      <!--     <%= form.label :workflow_state, class: "col-form-label" %> -->
      <!--   </div> -->
      <!--   <div class="col-md-9"> -->
      <!--     <%= form.select :workflow_state, Member.workflow_spec.states.keys, {include_blank: false}, {class: "form-control", disabled: !permitted_attributes.include?(:workflow_state)} %> -->
      <!--   </div> -->
      <!-- </div> -->
      <% end %>
    </fieldset>

    <fieldset class="col-md-6">
      <legend><%= t('members.new.contact') %></legend>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :email, class: "col-form-label" do %>

          <span class="badge badge-danger" data-toggle="tooltip" data-placement="right" title="<%= t('members.new.email_warning') %>"><%= t('activerecord.attributes.member.email') %> ⚠️</span>
          <% end %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :email, class: "form-control", disabled: !permitted_attributes.include?(:email) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :phone, class: "col-form-label" %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :phone, class: "form-control", disabled: !permitted_attributes.include?(:phone) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :address, class: "col-form-label" %>
        </div>
        <div class="col-md-10">
          <%= form.text_area :address, class: "form-control", disabled: !permitted_attributes.include?(:address) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :zipcode, class: "col-form-label" %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :zipcode, class: "form-control", disabled: !permitted_attributes.include?(:zipcode) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :city, class: "col-form-label" %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :city, class: "form-control", disabled: !permitted_attributes.include?(:city) %>
        </div>
      </div>
    </fieldset>

    <fieldset class="col-12">
      <div class="form-group row">
        <div class="col-md-10">
          <%= form.submit nil, class: 'btn btn-primary' %>
          <%= link_to 'Back', session[:return_to], class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/members/_import_modal.html.erb
<div class="modal fade" id="importMembersModal" tabindex="-1" role="dialog" aria-labelledby="importMembersModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <%= form_with url: import_members_url, method: :post do |form| %>
      <div class="modal-header">
        <h5 class="modal-title" id="importMembersModalTitle"><%= t('members.index.modals.import.title') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <div class="col-md-3">
            <%= form.label t('members.index.modals.import.file_input'), class: "col-form-label" %>
          </div>
          <div class="col-md-9">
            <%= form.file_field :import_file, accept: 'text/csv', class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('members.index.modals.import.buttons.cancel') %></button>
        <%= form.submit t('members.index.modals.import.buttons.import'), class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/members/edit.html.erb
<h1><%= t('members.update.title') %></h1>
<% permitted_attributes = can?(:manage, Member) ? Member::CREATION_FIELDS : Member::UPDATE_FIELDS %>
<%= render partial: "form", locals: {
             permitted_attributes: permitted_attributes,
             form_destination: {model: [@member]}
           }
%>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>

app/views/members/index.html.erb
<!-- Modal -->
<%= render partial: "import_modal" %>
<%= render partial: "export_modal" %>

<!-- Page -->

<h1><%= t('members.index.title') %></h1>

<div class="row mt-3">
  <div class="col-sm-6">
    <%= form_with method: "get" do |form| %>
      <div class="input-group mb-3">
        <%= form.text_field :search, placeholder: t('members.index.buttons.search'), value: @search, class: "form-control" %>
        <%= hidden_field_tag(:year, @year) %>
        <div class="input-group-append">
          <%= form.submit("🔎", class: 'btn btn-outline-secondary input-group-text', id: 'button-addon2') %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-6">
    <div class="dropdown float-sm-right mb-3">
      <% if can?(:destroy, Member) %>
        <%= button_tag(type: "submit",
                       data: { confirm: "Are you sure ?" },
                       form: "delete_members_form",
                       class: "btn btn-sm btn-outline-danger") do %>
          Delete members
        <% end %>
      <% end %>

      <% if can?(:import, Member) %>
      <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#exportMembersModal">
        <%= t('members.index.buttons.export') %>
      </button>
      <!-- <%= link_to request.query_parameters.merge(format: 'csv'), class: "btn btn-sm btn-outline-secondary" do %> -->
      <!--   <%= t('members.index.buttons.export') %> -->
      <!-- <% end %> -->
      <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#importMembersModal">
        <%= t('members.index.buttons.import') %>
      </button>
      <% end %>
      <a class="btn btn-<%= @years.first.year.to_i == @year.to_i ? 'success' : 'warning' %> btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if @year.to_i == 0 %>
        <%= t('activerecord.attributes.member.no_membership').pluralize %>
        <% else %>
        <%= t('activerecord.models.member').pluralize %> <%= @years.find { |m| m.year.to_i == @year.to_i }&.human_year %>
        <% end %>
      </a>

      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <% @years.select { |m| m.year.to_i != @year.to_i }.each do |m| %>
          <small>
            <%= link_to request.query_parameters.merge(year: m.year), class: "dropdown-item" do %>
              <%= t('activerecord.models.member').pluralize %> <%= m.human_year %>
            <% end %>
          </small>
        <% end %>
          <small>
            <%= link_to request.query_parameters.merge(year: :none), class: "dropdown-item" do %>
              <%= t('activerecord.attributes.member.no_membership').pluralize %>
            <% end %>
          </small>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <% if @active_members.present? %>
      <%= form_with id: "delete_members_form", url: batch_members_url, method: :delete do |f| %>
        <div class="table-responsive-sm">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col" colspan="2"><%= t('activerecord.attributes.member.first_name') %>
                  <%= order_link(:first_name, order: @order) %>
                </th>
                <th scope="col"><%= t('activerecord.attributes.member.last_name') %>
                  <%= order_link(:last_name, order: @order) %>
                </th>
                <th scope="col"><%= t('activerecord.attributes.member.workflow_state') %>
                  <%= order_link(:workflow_state, order: @order) %>
                </th>
                <th scope="col"><%= t('activerecord.attributes.member.created_at') %>
                  <%= order_link(:created_at, order: @order) %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @families.each do |family| %>
                <% family.each_with_index do |member, child| %>
                  <% if child > 0 %>
                    <tr class="clickable-row"></tr>
                  <% end %>
                  <tr class="clickable-row member-row">
                    <th scope="row"><%= f.check_box 'ids[]', {}, member.id, nil %></th>
                    <% if child > 0 %>
                    <td>⤷</td>
                    <td>
                    <% else %>
                    <td colspan="2">
                    <% end %>
                      <%= link_to member.first_name, member_url(member) %>
                    </td>
                    <td><%= link_to member.last_name, member_url(member) %></td>
                    <td><%= render_member_state_bootstrap_badge(member.workflow_state).html_safe %></td>
                    <td><%= l member.created_at, format: :short %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-6">
            <% if can?(:create, Member) %>
              <%= link_to "➕ #{t('members.index.buttons.create')}",
                          new_member_path,
                          class: 'btn btn-sm btn-primary float-right' %>
              <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <b>
        <% if @search.blank? %>
          <%= t('members.index.empty') %>
        <% else %>
          <%= t('members.index.empty_search', search: @search) %>
        <% end %>
      </b>
    <% end %>
  </div>
</div>

<%= render partial: "shared/pagination",
    locals: {
      collection: @active_members,
      current_page: @page,
      link_params: @index_params,
      per_page: @limit,
      offset: @offset,
      total: @total
    }
%>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>

app/views/members/new.html.erb
<h1><%= t('members.new.title') %></h1>

<%= render partial: "form", locals: {
             permitted_attributes: Member::CREATION_FIELDS,
             form_destination: {model: [@member]}
           }
%>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
<% end %>

app/views/members/show.html.erb
<div class="row mb-3">
  <div class="col">
    <p class="float-right">
      <%= link_to "#{t('members.show.buttons.edit')} 📝", edit_member_path(@member), class: 'btn btn-primary btn-sm' %>
    </p>

    <h1><%= emoji_sexe(@member.sexe) %> <%= t('members.show.title', name: @member.name) %></h1>

    <div class="float-none mb-3">
      <span class="text-muted font-italic">
        <small>
          <%= t('members.show.created_at', date: l(@member.created_at.to_date, format: :long)) %>
        </small>
          —
        <% if @sessions.present? %>
          <% current_session = @sessions.first %>
          <small>
            <span data-toggle="tooltip" data-placement="bottom" title="<%= current_session.user_agent %> (<%= current_session.remote_addr %>)">
              <%= t('members.show.last_connection_at', datetime: l(current_session.claimed_at, format: :long)) %>
            </span>
          </small>
        <% else %>
        <small class="font-weight-bold">
          Never logged-in
          </small>
        <% end %>
      </span>
      <div class="badges">
        <% if @member.latest_membership.present? %>
          <span class="badge badge-<%= @member.active? ? 'success' : 'warning' %>">Member <%= @member.latest_membership.human_year %></span>
        <% end %>
        <span class="badge badge-secondary" data-toggle="tooltip" data-placement="bottom" title="<%= t('members.show.date_of_birth', dob: @member.dob) %>">
          <%= t('members.show.age', age: @member.age) %>
        </span>
      <% if @member.email.present? %>
        <span class="badge badge-info">💌 <%= mail_to @member.email, @member.email, class: "text-light" %></span>
      <% end %>
      <% if @member.admin? %>
        <span class="badge badge-danger"><%= t('activerecord.attributes.member.roles.admin') %></span>
      <% end %>
      </div>
    </div>

    <table class="table address">
      <thead>
        <tr>
          <th><em><%= t('activerecord.attributes.member.phone') %></em></th>
          <th><em><%= t('activerecord.attributes.member.address') %></em></th>
          <th><em><%= t('activerecord.attributes.member.zipcode') %></em></th>
          <th><em><%= t('activerecord.attributes.member.city') %></em></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @member.phone %></td>
          <td><%= @member.address %></td>
          <td><%= @member.zipcode %></td>
          <td><%= @member.city %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<% if @member.parent_id.present? || @member.children.present? %>
<div class="row mb-3">
  <div class="col">
    <h2><%= t('members.show.family_list') %></h2>

    <ul class="list-group">
      <% parent = @member.parent %>
      <% ([parent || @member] + [parent&.children] + [@member.children]).flatten.compact.each do |member| %>
        <li class="list-group-item <%= @member == member ? 'bg-light' : '' %>">
          <%= link_to member.name, member_url(member), class: @member == member ? 'text-muted' : '' %>
          <% if member.parent_id.nil? %>
            <span class="badge badge-primary">parent</span>
          <% end%>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<% if @member.current_groups.present? %>
<div class="row mb-3">
  <div class="col">
    <h2><%= t('members.show.groups_list') %></h2>

    <ul class="list-group">
      <% @member.current_groups.each do |group| %>
      <li class="list-group-item"><%= link_to group.name, group_url(group) %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<% content_for :debug do %>
  <p><%= t('footer.debug.find_me', file: __FILE__) %></p>
  <p><%= @member %></p>
<% end %>